# Generated by Django 5.2.13 on 2026-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_date', models.DateField(blank=True, null=True)),
                ('sub_unit', models.CharField(max_length=255)),
                ('comm_type', models.CharField(help_text='e.g., Fantasy, Fiction, Self-help', max_length=100)),
                ('status_expiry', models.DateField(blank=True, null=True)),
                ('station_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
