# Generated by Django 5.2.13 on 2026-04-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('config', '0002_personnel_alter_assetstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='par_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='config.parrecord'),
        ),
    ]
