# Generated by Django 5.2.13 on 2026-05-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('config', '0002_personnel_alter_assetstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='par_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_assignments', to='config.parrecord'),
        ),
        migrations.AlterModelTable(
            name='communication',
            table='communications_communication',
        ),
        migrations.CreateModel(
            name='CommunicationPARRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_number', models.CharField(max_length=100)),
                ('fund_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(max_length=150)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_par_records', related_query_name='communication_par_record', to='communications.communication')),
            ],
            options={
                'db_table': 'communications_parrecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
