# Generated by Django 5.2.13 on 2026-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communication_par_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='frequency_range',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='stock_level',
        ),
        migrations.AddField(
            model_name='communication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='radio_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='remarks',
            field=models.CharField(default='VALIDATED', max_length=100),
        ),
    ]
