# Generated by Django 5.2.13 on 2026-05-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_communication_frequency_range_and_more'),
        ('config', '0003_icsrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationparrecord',
            name='fund_cluster',
        ),
        migrations.AddField(
            model_name='communication',
            name='ics_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_ics_assignments', to='config.icsrecord'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='par_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_par_assignments', to='config.parrecord'),
        ),
        migrations.CreateModel(
            name='CommunicationICSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ics_number', models.CharField(max_length=100)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(max_length=150)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_ics_records', related_query_name='communication_ics_record', to='communications.communication')),
            ],
            options={
                'db_table': 'communications_icsrecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
