# Generated by Django 5.2.13 on 2026-04-22 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.asset')),
                ('type', models.CharField(max_length=100)),
                ('caliber', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('config.asset',),
        ),
    ]
