# Generated by Django 5.2.13 on 2026-05-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firearm',
            options={'verbose_name': 'Firearm'},
        ),
        migrations.AddField(
            model_name='firearm',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='faid_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='issuing_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='subunit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='validated',
            field=models.CharField(choices=[('VALIDATED', 'Validated'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='firearm',
            table='Firearm_Details',
        ),
        migrations.CreateModel(
            name='FirearmPARRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_number', models.CharField(max_length=50)),
                ('fund_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_to', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firearm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firearms_par_records', to='firearms.firearm')),
            ],
            options={
                'db_table': 'firearms_parrecord',
            },
        ),
    ]
