# Generated by Django 5.2.13 on 2026-04-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firearm',
            options={'verbose_name': 'Firearm'},
        ),
        migrations.AlterModelTable(
            name='firearm',
            table='Firearm_Details',
        ),
    ]
