# Generated by Django 5.2.13 on 2026-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0002_alter_firearm_options_alter_firearm_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearm',
            name='faid_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
