# Generated by Django 5.2.13 on 2026-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0003_firearm_faid_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearm',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='issuing_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='subunit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='validated',
            field=models.CharField(choices=[('VALIDATED', 'Validated'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
