# Generated by Django 5.2.13 on 2026-05-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0004_firearm_assigned_to_firearm_issuing_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirearmPARRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_number', models.CharField(max_length=50)),
                ('fund_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_to', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firearm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firearms_par_records', to='firearms.firearm')),
            ],
            options={
                'db_table': 'firearms_parrecord',
            },
        ),
    ]
