# Generated by Django 6.0.4 on 2026-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('firearm', 'Firearm'), ('communication', 'Communication'), ('investigative', 'Investigative')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('sub_unit', models.CharField(max_length=100)),
                ('comm_type', models.CharField(max_length=100)),
                ('expiry_status', models.DateField()),
                ('station_url', models.URLField()),
            ],
        ),
    ]
