# Generated by Django 5.2.13 on 2026-04-22 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalItem',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.asset')),
                ('disposal_reason', models.TextField(blank=True, db_column='disposal_reason', help_text='Reason for disposal/BER', null=True)),
                ('disposal_date', models.DateTimeField(auto_now_add=True, db_column='disposal_date')),
                ('days_overdue', models.IntegerField(blank=True, db_column='days_overdue', default=0, null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', null=True)),
                ('processed_by', models.ForeignKey(blank=True, db_column='processed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disposal Item',
                'db_table': 'disposal_disposalitems',
            },
            bases=('config.asset',),
        ),
    ]
