# Generated by Django 5.2.13 on 2026-04-26 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0002_disposalactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('disposal_reason', models.TextField()),
                ('original_expiry_date', models.DateTimeField()),
                ('removal_date', models.DateTimeField(auto_now_add=True)),
                ('removed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disposed Asset Archive',
                'ordering': ['-removal_date'],
            },
        ),
    ]
