# Generated by Django 5.2.13 on 2026-04-26 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_asset_status'),
        ('disposal', '0003_disposedarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposedarchive',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='disposedarchive',
            name='category',
        ),
        migrations.RemoveField(
            model_name='disposedarchive',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='disposedarchive',
            name='original_expiry_date',
        ),
        migrations.RemoveField(
            model_name='disposedarchive',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='disposedarchive',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='config.asset'),
            preserve_default=False,
        ),
    ]
