# Generated by Django 5.2.13 on 2026-04-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0004_remove_disposedarchive_asset_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisposedArchive',
        ),
    ]
