# Generated by Django 5.2.13 on 2026-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0005_delete_disposedarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalactivitylog',
            name='disposal_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
