# Generated by Django 5.2.13 on 2026-04-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_personnel_alter_assetstatus_options_and_more'),
        ('disposal', '0006_disposalactivitylog_disposal_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposalitem',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='disposalitem',
            name='personnel_assigned',
            field=models.ForeignKey(db_column='personnel_assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.personnel'),
        ),
        migrations.AlterField(
            model_name='disposalactivitylog',
            name='action_type',
            field=models.CharField(choices=[('REMOVE', 'Finalized Removal'), ('UPDATE', 'Updated Disposal Info'), ('FLAGGED', 'Flagged for Disposal')], default='REMOVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='disposalitem',
            name='disposal_reason',
            field=models.TextField(blank=True, db_column='disposal_reason', default=1, help_text='Reason for disposal/BER'),
            preserve_default=False,
        ),
    ]
