# Generated by Django 5.2.13 on 2026-04-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0007_remove_disposalitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalitem',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
