# Generated by Django 5.2.13 on 2026-04-22 02:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('status_id', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='StatusName', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Statuses',
                'db_table': 'Asset_Status',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateField()),
                ('property_no', models.CharField(max_length=100, unique=True)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('status', models.ForeignKey(blank=True, db_column='StatusID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='config.assetstatus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='config.category')),
            ],
        ),
        migrations.CreateModel(
            name='PARRecord',
            fields=[
                ('par_id', models.AutoField(db_column='ParID', primary_key=True, serialize=False)),
                ('par_number', models.CharField(db_column='PAR_Number', max_length=100, unique=True)),
                ('date_issued', models.DateField(db_column='Date_Issued', default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, db_column='Return_Date', null=True)),
                ('condition_on_issuance', models.TextField(db_column='Condition_on_Issuance')),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
                ('asset', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, related_name='par_records', to='config.asset')),
                ('issued_to', models.ForeignKey(db_column='Issued_to_ID', on_delete=django.db.models.deletion.PROTECT, related_name='received_assets', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_pars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PAR Record',
                'verbose_name_plural': 'PAR Records',
                'db_table': 'PAR_Record',
            },
        ),
    ]
