# Generated by Django 5.2.13 on 2026-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='office',
            field=models.CharField(blank=True, db_column='Office', max_length=100, null=True),
        ),
    ]
