# Generated by Django 5.2.13 on 2026-05-10 17:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel_id', models.BigAutoField(db_column='PersonnelID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('rank', models.CharField(db_column='Rank', max_length=100)),
                ('badge_number', models.CharField(db_column='Badge_Number', max_length=50, unique=True)),
                ('department', models.CharField(db_column='Department', max_length=100)),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='asset',
            name='office',
            field=models.CharField(blank=True, db_column='Office', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(db_column='StatusID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='config.assetstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='par_id',
            field=models.BigAutoField(db_column='ParID', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ICSRecord',
            fields=[
                ('ics_id', models.AutoField(db_column='ics_id', primary_key=True, serialize=False)),
                ('ics_number', models.CharField(db_column='ICS_Number', max_length=100, unique=True)),
                ('date_issued', models.DateField(db_column='Date_Issued', default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, db_column='Return_Date', null=True)),
                ('condition_on_issuance', models.TextField(db_column='Condition_on_Issuance')),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
                ('asset', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, related_name='ics_records', to='config.asset')),
                ('processed_by', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_ics', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(db_column='Issued_to_ID', on_delete=django.db.models.deletion.PROTECT, related_name='received_ics_assets', to='config.personnel')),
            ],
            options={
                'verbose_name': 'ICS Record',
                'verbose_name_plural': 'ICS Records',
                'db_table': 'ICS_Record',
            },
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='issued_to',
            field=models.ForeignKey(db_column='Issued_to_ID', on_delete=django.db.models.deletion.PROTECT, related_name='received_assets', to='config.personnel'),
        ),
    ]
