# Generated by Django 5.2.13 on 2026-04-26 06:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel_id', models.BigAutoField(db_column='PersonnelID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('rank', models.CharField(db_column='Rank', max_length=100)),
                ('badge_number', models.CharField(db_column='Badge_Number', max_length=50, unique=True)),
                ('department', models.CharField(db_column='Department', max_length=100)),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='assetstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='assetstatus',
            name='status_id',
            field=models.BigAutoField(db_column='StatusID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PARRecord',
            fields=[
                ('par_id', models.AutoField(db_column='ParID', primary_key=True, serialize=False)),
                ('par_number', models.CharField(db_column='PAR_Number', max_length=100, unique=True)),
                ('date_issued', models.DateField(db_column='Date_Issued', default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, db_column='Return_Date', null=True)),
                ('condition_on_issuance', models.TextField(db_column='Condition_on_Issuance')),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
                ('asset', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, related_name='par_records', to='config.asset')),
                ('processed_by', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_pars', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(db_column='Issued_to_ID', on_delete=django.db.models.deletion.PROTECT, related_name='received_assets', to='config.personnel')),
            ],
            options={
                'verbose_name': 'PAR Record',
                'verbose_name_plural': 'PAR Records',
                'db_table': 'PAR_Record',
            },
        ),
    ]
