# Generated by Django 5.2.13 on 2026-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
