# Generated by Django 5.2.13 on 2026-04-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel_id', models.BigAutoField(db_column='PersonnelID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('rank', models.CharField(db_column='Rank', max_length=100)),
                ('badge_number', models.CharField(db_column='Badge_Number', max_length=50, unique=True)),
                ('department', models.CharField(db_column='Department', max_length=100)),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(db_column='StatusID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='config.assetstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='par_id',
            field=models.BigAutoField(db_column='ParID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='issued_to',
            field=models.ForeignKey(db_column='Issued_to_ID', on_delete=django.db.models.deletion.PROTECT, related_name='received_assets', to='config.personnel'),
        ),
    ]
