# Generated by Django 5.2.13 on 2026-05-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_personnel_alter_assetstatus_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PARRecord',
        ),
    ]
