# Generated by Django 5.2.13 on 2026-04-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_asset_office'),
    ]

    operations = []
