# Generated by Django 5.2.13 on 2026-05-08 14:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_personnel_alter_assetstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICSRecord',
            fields=[
                ('ics_id', models.AutoField(db_column='IcsID', primary_key=True, serialize=False)),
                ('ics_number', models.CharField(db_column='ICS_Number', max_length=100, unique=True)),
                ('date_issued', models.DateField(db_column='Date_Issued', default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, db_column='Return_Date', null=True)),
                ('condition_on_issuance', models.TextField(db_column='Condition_on_Issuance')),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
                ('asset', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, related_name='ics_records', to='config.asset')),
                ('issued_to', models.ForeignKey(db_column='Issued_to_ID', on_delete=django.db.models.deletion.PROTECT, related_name='received_ics_assets', to='config.personnel')),
                ('processed_by', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_ics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICS Record',
                'verbose_name_plural': 'ICS Records',
                'db_table': 'ICS_Record',
            },
        ),
    ]
