# Generated by Django 5.2.13 on 2026-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_asset_id_alter_assetstatus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='status_id',
            field=models.IntegerField(db_column='StatusID', primary_key=True, serialize=False),
        ),
    ]
