# Generated by Django 5.2.13 on 2026-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_assetstatus_id_alter_assetstatus_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstatus',
            name='status_id',
            field=models.BigAutoField(db_column='StatusID', primary_key=True, serialize=False),
        ),
    ]
