# Generated by Django 5.2.13 on 2026-05-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_assetstatus_id_asset_office_asset_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='config.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icsrecord',
            name='ics_id',
            field=models.AutoField(db_column='ICS_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
    ]
