# Generated by Django 5.2.13 on 2026-04-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_assetstatus_status_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetstatus',
            options={},
        ),
    ]
