# Generated by Django 5.2.13 on 2026-04-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_assetstatus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetstatus',
            old_name='status_name',
            new_name='Status_Name',
        ),
    ]
