# Generated by Django 5.2.13 on 2026-04-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_rename_status_name_assetstatus_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(db_column='StatusID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='config.assetstatus'),
            preserve_default=False,
        ),
    ]
