# Generated by Django 5.2.13 on 2026-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_asset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstatus',
            name='Status_Name',
        ),
        migrations.AddField(
            model_name='assetstatus',
            name='status_name',
            field=models.CharField(db_column='Status_Name', default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
