# Generated by Django 5.2.13 on 2026-04-25 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(default='TEMP-ID', max_length=50, unique=True)),
                ('kind', models.CharField(default='Special Purpose Vehicle', max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('conduction_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(max_length=100, unique=True)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('No Record', 'No Record'), ('For PMS', 'For PMS'), ('For Registration', 'For Registration'), ('For Insurance', 'For Insurance'), ('Repair Required', 'Repair Required'), ('Upcoming PMS', 'Upcoming PMS')], default='Good', max_length=50)),
                ('latest_odo', models.IntegerField(default=0)),
                ('registration_renewal_date', models.DateField(blank=True, null=True)),
                ('insurance_renewal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PARRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_number', models.CharField(max_length=100, unique=True)),
                ('issued_to', models.CharField(max_length=255)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pars', to='mobility.vehicle')),
            ],
        ),
    ]
