# Generated by Django 5.2.13 on 2026-05-14 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'config_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INFO', 'Info'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='INFO', max_length=10)),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('primary_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Pick-up', 'Pick-up'), ('Van', 'Van'), ('Motorcycle', 'Motorcycle'), ('Multi-Cab', 'Multi-Cab'), ('Utility Vehicle', 'Utility Vehicle'), ('Mobile Laboratory', 'Mobile Laboratory'), ('Service Vehicle', 'Service Vehicle'), ('Patrol Vehicle', 'Patrol Vehicle'), ('Transport Vehicle', 'Transport Vehicle'), ('Rescue Vehicle', 'Rescue Vehicle'), ('Tactical Vehicle', 'Tactical Vehicle')], max_length=50, null=True)),
                ('make_model', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('conduction_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Serviceable', 'Serviceable'), ('Unserviceable', 'Unserviceable'), ('BER', 'BER'), ('Disposed', 'Disposed')], default='Serviceable', max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_renewal_date', models.DateField(blank=True, null=True)),
                ('insurance_renewal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_details', to='config.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PARRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_number', models.CharField(max_length=50, unique=True)),
                ('issued_to', models.CharField(max_length=100)),
                ('date_acquired', models.DateField(db_column='date_acquired', default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_records', to='mobility.vehicle')),
            ],
            options={
                'verbose_name': 'PAR Record',
                'verbose_name_plural': 'PAR Records',
                'ordering': ['-date_acquired'],
            },
        ),
    ]
