# Generated by Django 5.2.13 on 2026-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Maintenance', 'Maintenance')], default='Available', max_length=25)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('chassis_number', models.CharField(blank=True, max_length=100)),
                ('registration_renewal_date', models.DateField(blank=True, null=True)),
                ('insurance_renewal_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['vehicle_id'],
            },
        ),
    ]
