# Generated by Django 5.2.13 on 2026-05-09 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parrecord',
            options={'ordering': ['-date_acquired'], 'verbose_name': 'PAR Record', 'verbose_name_plural': 'PAR Records'},
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='date_issued',
            field=models.DateField(db_column='date_issued', default=django.utils.timezone.now),
        ),
        migrations.RenameField(
            model_name='parrecord',
            old_name='date_issued',
            new_name='date_acquired',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='conduction_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Serviceable', 'Serviceable'), ('Unserviceable', 'Unserviceable'), ('BER', 'BER'), ('Disposed', 'Disposed')], default='Serviceable', max_length=50),
        ),
    ]
