# Generated by Django 5.2.13 on 2026-05-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'config_asset',
                'managed': False,
            },
        ),
    ]
