# Generated by Django 5.2.13 on 2026-05-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_configasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_par_records', to='mobility.vehicle'),
        ),
    ]
