# Generated by Django 5.2.13 on 2026-05-09 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_alter_parrecord_options_alter_parrecord_date_issued_and_more'),
    ]

    operations = [

    ]
