# Generated by Django 5.2.13 on 2026-04-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='insurance_renewal_date',
            new_name='last_pms_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='registration_renewal_date',
            new_name='next_pms_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='latest_odo',
            new_name='odometer_reading',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='parrecord',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('EMAIL', 'Email Sent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='issued_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='par_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_records', to='mobility.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='conduction_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Good', 'Good Condition'), ('Upcoming PMS', 'Upcoming PMS'), ('For PMS', 'For PMS'), ('Repair Required', 'Repair Required'), ('For Registration', 'For Registration Renewal'), ('No Record', 'No Maintenance Record')], default='No Record', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
