# Generated by Django 5.2.13 on 2026-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0003_alter_activitylog_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='asset_id',
            field=models.IntegerField(blank=True, help_text='ID of the related Asset from the inventory', null=True),
        ),
    ]
