# Generated by Django 5.2.13 on 2026-05-09 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0003_remove_parrecord_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrecord',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='parrecord',
            name='fund_cluster',
        ),
        migrations.RemoveField(
            model_name='parrecord',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='alternative_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='classification',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Pick-up', 'Pick-up'), ('Van', 'Van'), ('Motorcycle', 'Motorcycle'), ('Multi-Cab', 'Multi-Cab'), ('Utility Vehicle', 'Utility Vehicle'), ('Mobile Laboratory', 'Mobile Laboratory'), ('Service Vehicle', 'Service Vehicle'), ('Patrol Vehicle', 'Patrol Vehicle'), ('Transport Vehicle', 'Transport Vehicle'), ('Rescue Vehicle', 'Rescue Vehicle'), ('Tactical Vehicle', 'Tactical Vehicle')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_model',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='primary_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
