# Generated by Django 5.2.13 on 2026-05-11 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0004_remove_parrecord_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrecord',
            name='date_acquired',
            field=models.DateField(db_column='date_acquired', default=django.utils.timezone.now),
        ),
    ]
