# Generated by Django 5.2.13 on 2026-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0005_remove_vehicle_color_remove_vehicle_last_pms_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Good Condition', 'Good Condition'), ('For Registration', 'For Registration'), ('For Insurance', 'For Insurance'), ('For PMS', 'For PMS'), ('For Repair', 'For Repair'), ('No Maintenance Record', 'No Maintenance Record')], default='No Maintenance Record', max_length=50),
        ),
    ]
