# Generated by Django 5.2.13 on 2026-04-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'config_asset',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_details', to='mobility.configasset'),
        ),
    ]
