# Generated by Django 5.2.13 on 2026-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0007_configasset_remove_vehicle_asset_id_vehicle_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parrecord',
            options={'ordering': ['-date_issued'], 'verbose_name': 'PAR Record', 'verbose_name_plural': 'PAR Records'},
        ),
        migrations.AddField(
            model_name='parrecord',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parrecord',
            name='fund_cluster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parrecord',
            name='reference_no',
            field=models.CharField(blank=True, help_text='Supply Directive NR', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
