# Generated by Django 6.0.4 on 2026-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0009_activitylog_user_alter_parrecord_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Good Condition', 'Good Condition'), ('For Registration', 'For Registration'), ('For Insurance', 'For Insurance'), ('For PMS', 'For PMS'), ('For Repair', 'For Repair'), ('No Maintenance Record', 'No Maintenance Record'), ('Disposed', 'Disposed')], default='No Maintenance Record', max_length=50),
        ),
    ]
