# Generated by Django 6.0.4 on 2026-05-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_personnel_alter_assetstatus_options_and_more'),
        ('mobility', '0010_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_details', to='config.asset'),
        ),
        migrations.DeleteModel(
            name='ConfigAsset',
        ),
    ]
