# Generated by Django 5.2.13 on 2026-05-06 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_delete_parrecord'),
        ('mobility', '0012_configasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigAsset',
        ),
        migrations.AlterModelOptions(
            name='parrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parrecord',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='odometer_reading',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AddField(
            model_name='parrecord',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latest_odo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='issued_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parrecord',
            name='par_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='asset',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='config.asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='conduction_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kind',
            field=models.CharField(default='Vehicle', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='Good Condition', max_length=50),
        ),
    ]
