# Generated by Django 5.2.13 on 2026-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('editor', 'Editor')], max_length=100, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
