# Generated by Django 5.2.13 on 2026-04-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigativeDetails',
            fields=[
                ('asset_id', models.ForeignKey(db_column='asset_ptr_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='investigative_details', serialize=False, to='config.asset')),
                ('item_description', models.TextField(blank=True, db_column='Item_Description', null=True)),
                ('par_id', models.CharField(blank=True, db_column='ParID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Investigative_Details',
            },
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('inspection_id', models.AutoField(db_column='InspectionID', primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(db_column='Inspection_Date')),
                ('compliance_status', models.CharField(db_column='Compliance_Status', max_length=100)),
                ('next_inspection_date', models.DateField(blank=True, db_column='Next_Inspection_Date', null=True)),
                ('inspector_id', models.CharField(db_column='InspectorID', max_length=100)),
                ('asset', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, related_name='inspection_logs', to='config.asset')),
            ],
            options={
                'db_table': 'Inspection_Log',
            },
        ),
    ]
