# Generated by Django 5.2.13 on 2026-05-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestigativeEquipment', '0001_initial'),
        ('config', '0002_personnel_alter_assetstatus_options_asset_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigativedetails',
            name='office',
            field=models.CharField(blank=True, db_column='Office', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ICSRecord',
            fields=[
                ('ics_id', models.AutoField(primary_key=True, serialize=False)),
                ('ics_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inves_ics_records', to='config.asset')),
            ],
            options={
                'db_table': 'Investigative_ICS_Record',
            },
        ),
    ]
