# Generated by Django 5.2.13 on 2026-05-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestigativeEquipment', '0002_investigativedetails_office_icsrecord'),
        ('config', '0004_alter_asset_category_alter_asset_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigativeActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigative', models.ForeignKey(db_column='asset_ptr_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='InvestigativeEquipment.investigativedetails')),
            ],
            options={
                'db_table': 'Investigative_Activity_Log',
            },
        ),
        migrations.CreateModel(
            name='InvestigativePARRecord',
            fields=[
                ('par_id', models.AutoField(primary_key=True, serialize=False)),
                ('par_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inves_par_records', to='config.asset')),
            ],
            options={
                'db_table': 'Investigative_PAR_Record',
            },
        ),
    ]
