# Generated by Django 5.2.13 on 2026-05-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestigativeEquipment', '0003_investigativeactivitylog_investigativeparrecord'),
        ('config', '0004_alter_asset_category_alter_asset_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigativeactivitylog',
            name='investigative',
        ),
        migrations.AddField(
            model_name='investigativeactivitylog',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_ptr_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigative_activity_logs', to='config.asset'),
        ),
    ]
